version: '3.7'
services:
  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=liang
      - POSTGRES_PASSWORD=abc
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_USER=liang
      - PG_PASSWORD=abc
      - PG_PORT=5432
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis
      - api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
